version: '2'

volumes:
    logs:
        driver: local



services:
    slim:
        build:
            context: ./
            dockerfile: Dockerfile
        image: boundary:supermarket-api
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
    db:
        image: postgres:12-alpine
        restart: always
